<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phims')->truncate();

        $trailer = 'https://www.youtube.com/watch?v=l3JdTYIHn-o';
        $daoDien = 'Công ty TNHH Chộ Đó Foods';
        $quocGia = '120 Yên Lãng';
        $nhaSanXuat = 'Chộ Đó';
        $hinhAnh = 'https://voz.vn/attachments/542754057_1467285577853420_8471185407916019492_n-jpg.3225827/';

        DB::table('phims')->insert([
            [
                'id' => 1,
                'ten_phim' => 'Khô gà loại 1',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Khô là lá chanh',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 200g',
                'ngay_phat_hanh' => '2025-01-01',
                'thoi_luong' => 36000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'ten_phim' => 'Khô gà loại 2',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Bã mía độ thành khô gà',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 250g',
                'ngay_phat_hanh' => '2025-01-05',
                'thoi_luong' => 63000,
                'mo_ta' => "MƯỢN TÂY DẠY TÀY\nThằng tây ngồi cạnh thằng tày\nThằng tây khẽ hỏi \"Sao mày từ cha?\"\nThằng tày mới mở lòng ra\n\"Tại vì lão có vợ ba tây à\".\nThằng tây khoái chí cười khà\n\"Vợ ba, vợ bốn ấy là việc ông\nPhận mày chữ Hiếu đếch xong\nMất luôn chữ Đức, đi tong chữ Tài\".\nTày buông một tiếng thở dài\n\"Tiền tao trong thẻ xài hoài chẳng vơi\nChữ Tài, Đức, Hiếu buông lơi\nTao mang chữ Lý để chơi với đời\".",
                'noi_dung' => "MƯỢN TÂY DẠY TÀY\nThằng tây ngồi cạnh thằng tày\nThằng tây khẽ hỏi \"Sao mày từ cha?\"\nThằng tày mới mở lòng ra\n\"Tại vì lão có vợ ba tây à\".\nThằng tây khoái chí cười khà\n\"Vợ ba, vợ bốn ấy là việc ông\nPhận mày chữ Hiếu đếch xong\nMất luôn chữ Đức, đi tong chữ Tài\".\nTày buông một tiếng thở dài\n\"Tiền tao trong thẻ xài hoài chẳng vơi\nChữ Tài, Đức, Hiếu buông lơi\nTao mang chữ Lý để chơi với đời\".",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'ten_phim' => 'Khô gà đè tem',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Khô gà Tàu đè tem',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 500g',
                'ngay_phat_hanh' => '2025-01-10',
                'thoi_luong' => 3636363,
                'mo_ta' => "Làm con chữ hiếu phải tròn\nLỡ mai không được còn nhìn thấy cha\nNgười dưng thì lại vị tha\nNgười nhà rút một thịt lại ra thế này.\nMùa xuân mùa của sum vầy\nỞ xa đến mấy cũng bay về nhà\nThế mà có kẻ từ cha\nTệ hơn cả Tú Sê Na đi tù.\nCó mắt nhưng chẳng khác mù\nLàm con phải hiếu cho dù ra sao\nĐừng mang cái vẻ thanh cao\nRồi từ cha mẹ khác nào sức sinh.\nKhôn ngoan thấu lý đạt tình\nBiết ơn cha mẹ gia đình ấm êm\nĐừng 10 giờ tối mỗi đêm\nMà lên bêu rếu và blame cha mình.",
                'noi_dung' => "Làm con chữ hiếu phải tròn\nLỡ mai không được còn nhìn thấy cha\nNgười dưng thì lại vị tha\nNgười nhà rút một thịt lại ra thế này.\nMùa xuân mùa của sum vầy\nỞ xa đến mấy cũng bay về nhà\nThế mà có kẻ từ cha\nTệ hơn cả Tú Sê Na đi tù.\nCó mắt nhưng chẳng khác mù\nLàm con phải hiếu cho dù ra sao\nĐừng mang cái vẻ thanh cao\nRồi từ cha mẹ khác nào sức sinh.\nKhôn ngoan thấu lý đạt tình\nBiết ơn cha mẹ gia đình ấm êm\nĐừng 10 giờ tối mỗi đêm\nMà lên bêu rếu và blame cha mình.",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'ten_phim' => 'Khô Gà Chua Cay',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Vị mặn béo đặc trưng của lòng đỏ trứng muối nghiền mịn bao quanh sợi gà.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Hũ 1kg',
                'ngay_phat_hanh' => '2025-01-15',
                'thoi_luong' => 119000,
                'mo_ta' => "Một cái chết truyền thông\nCác bạn có thấy nó rất phiền không?\nMất quyền, mất tiền, lên án, phê phán\nLôi hết cả cộng đồng bỏ cha\nĐể cả cộng đồng bợ không\nXây trường như hồi trước tốn gạch không?\nCác bạn chưa hiểu mình những chộ truyền thông\nĐể hùa theo một cách rất viển vông\nStreamer nước mình vất vả\nNhưng họ dâng hiến tất cả\nBạn phải đè tem vật vã\nRa xã hội bán khô gà thật đã\nBỏ bàn phím ra, đóng PC vào\nĐi 2 năm chộ đó tao xem nào, tao chả sợ quá\nTrên mạng thì bảo bỏ chơi\nRa đời thì hẳn hai hơi cái gì?\nXin thưa, từ xưa đến nay\nShisha là loại ma tuý duy nhất mà tao chơi!\nCác bạn NPC có muốn mình live nữa không?",
                'noi_dung' => "Một cái chết truyền thông\nCác bạn có thấy nó rất phiền không?\nMất quyền, mất tiền, lên án, phê phán\nLôi hết cả cộng đồng bỏ cha\nĐể cả cộng đồng bợ không\nXây trường như hồi trước tốn gạch không?\nCác bạn chưa hiểu mình những chộ truyền thông\nĐể hùa theo một cách rất viển vông\nStreamer nước mình vất vả\nNhưng họ dâng hiến tất cả\nBạn phải đè tem vật vã\nRa xã hội bán khô gà thật đã\nBỏ bàn phím ra, đóng PC vào\nĐi 2 năm chộ đó tao xem nào, tao chả sợ quá\nTrên mạng thì bảo bỏ chơi\nRa đời thì hẳn hai hơi cái gì?\nXin thưa, từ xưa đến nay\nShisha là loại ma tuý duy nhất mà tao chơi!\nCác bạn NPC có muốn mình live nữa không?",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'ten_phim' => 'Khô Gà 36',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Mang hương vị chua cay kiểu Thái, thơm mùi riềng và lá chanh Thái.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 300g',
                'ngay_phat_hanh' => '2025-02-01',
                'thoi_luong' => 109000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'ten_phim' => 'Khô Gà Cay Siêu Cấp',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Tẩm ướp bột cà ri vàng ươm, hương vị nồng nàn lạ miệng.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 400g',
                'ngay_phat_hanh' => '2025-01-01',
                'thoi_luong' => 125000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'ten_phim' => 'Khô Gà Vàng Ươm',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Rắc thêm hạt mè rang thơm phức, khi ăn tạo cảm giác bùi bùi.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Combo 5x200g',
                'ngay_phat_hanh' => '2025-01-05',
                'thoi_luong' => 99000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'ten_phim' => 'Khô Gà Nướng Thơm',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Vị cay nồng của ớt sa tế và màu đỏ dầu điều rất kích thích.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 350g',
                'ngay_phat_hanh' => '2025-01-10',
                'thoi_luong' => 139000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'ten_phim' => 'Khô Gà Chua Cay',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Sử dụng gia vị "hạt tiêu rừng" Tây Bắc, có mùi thơm rất riêng biệt và hơi tê đầu lưỡi.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 250g',
                'ngay_phat_hanh' => '2025-01-15',
                'thoi_luong' => 99000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'ten_phim' => 'Khô Gà Cao Bằng',
                'dao_dien' => $daoDien,
                'dien_vien' => 'Có mùi thơm khói nhẹ và vị sốt nướng đậm đà kiểu Âu.',
                'hinh_anh' => $hinhAnh,
                'trailer' => $trailer,
                'quoc_gia' => $quocGia,
                'ngon_ngu' => 'Gói 250g',
                'ngay_phat_hanh' => '2025-02-01',
                'thoi_luong' => 99000,
                'mo_ta' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'noi_dung' => "THE INVITATION\nXin gửi bạn một lời thách đấu\nHai ta thi nấu khẩu thành thơ\nTiểu với Đại, không còn bơ vơ\nCó khi ta lại, nên tơ không thành\nMình biết bạn anti anh Ộ\nTôi bị kick từ chộ đó ra\nNhư Rô vẩu với Kaka,\nĐôi ta hợp sức, chết cha anh tày",
                'nha_san_xuat' => $nhaSanXuat,
                'tinh_trang' => 1,
                'id_the_loai' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
