FROM node:18-alpine

WORKDIR /app

# Copy all frontend files first
COPY khoa_22_fe/frontend/ /temp/

# Copy to /app
RUN cp -r /temp/* /app/ && rm -rf /temp/

RUN npm install

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host"]
